export * from "./getEitherT"
export { map, mapLeft, bimap } from "./functor"
export { ap } from "./applicative"
export { flatMap } from "./monad"
export { left, leftF } from "./left"
export { right, rightF } from "./right"
export { match } from "./match"
export { swap } from "./swap"
export { toUnion } from "./toUnion"
