export * from "./getOptionT"
export { map } from "./functor"
export { ap } from "./applicative"
export { flatMap } from "./monad"
export { some } from "./some"
export { zero } from "./zero"
export { match } from "./match"
export { fromF } from "./fromF"
