import * as readonlyArray from "../modules/ReadonlyArray"
import * as option from "../modules/Option"
import * as eq from "../types/Eq"
import { LazyArg } from "../types/utils"
import { pipe } from "./flow"

interface Matchers<A> {
  <B>(ab: (a: A) => B): (a: A) => B
  <B, C = B>(ab: (a: A) => B, c: [A, LazyArg<C>]): (a: A) => B | C
  <B, C = B, D = C>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
  ): (a: A) => B | C | D
  <B, C = B, D = C, E = D>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
  ): (a: A) => B | C | D | E
  <B, C = B, D = C, E = D, F = E>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
  ): (a: A) => B | C | D | E | F
  <B, C = B, D = C, E = D, F = E, G = F>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
  ): (a: A) => B | C | D | E | F | G
  <B, C = B, D = C, E = D, F = E, G = F, H = G>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
  ): (a: A) => B | C | D | E | F | G | H
  <B, C = B, D = C, E = D, F = E, G = F, H = G, I = H>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
  ): (a: A) => B | C | D | E | F | G | H | I
  <B, C = B, D = C, E = D, F = E, G = F, H = G, I = H, J = I>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
  ): (a: A) => B | C | D | E | F | G | H | I | J
  <B, C = B, D = C, E = D, F = E, G = F, H = G, I = H, J = I, K = J>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K
  <B, C = B, D = C, E = D, F = E, G = F, H = G, I = H, J = I, K = J, L = K>(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L | M
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L | M | N
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
    O = N,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
    o: [A, LazyArg<O>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L | M | N | O
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
    O = N,
    P = O,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
    o: [A, LazyArg<O>],
    p: [A, LazyArg<P>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L | M | N | O | P
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
    O = N,
    P = O,
    Q = P,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
    o: [A, LazyArg<O>],
    p: [A, LazyArg<P>],
    q: [A, LazyArg<Q>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
    O = N,
    P = O,
    Q = P,
    R = Q,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
    o: [A, LazyArg<O>],
    p: [A, LazyArg<P>],
    q: [A, LazyArg<Q>],
    r: [A, LazyArg<R>],
  ): (a: A) => B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
    O = N,
    P = O,
    Q = P,
    R = Q,
    S = R,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
    o: [A, LazyArg<O>],
    p: [A, LazyArg<P>],
    q: [A, LazyArg<Q>],
    r: [A, LazyArg<R>],
    s: [A, LazyArg<S>],
  ): (
    a: A,
  ) => B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S
  <
    B,
    C = B,
    D = C,
    E = D,
    F = E,
    G = F,
    H = G,
    I = H,
    J = I,
    K = J,
    L = K,
    M = L,
    N = M,
    O = N,
    P = O,
    Q = P,
    R = Q,
    S = R,
    T = S,
  >(
    ab: (a: A) => B,
    c: [A, LazyArg<C>],
    d: [A, LazyArg<D>],
    e: [A, LazyArg<E>],
    f: [A, LazyArg<F>],
    g: [A, LazyArg<G>],
    h: [A, LazyArg<H>],
    i: [A, LazyArg<I>],
    j: [A, LazyArg<J>],
    k: [A, LazyArg<K>],
    l: [A, LazyArg<L>],
    m: [A, LazyArg<M>],
    n: [A, LazyArg<N>],
    o: [A, LazyArg<O>],
    p: [A, LazyArg<P>],
    q: [A, LazyArg<Q>],
    r: [A, LazyArg<R>],
    s: [A, LazyArg<S>],
    t: [A, LazyArg<T>],
  ): (
    a: A,
  ) => B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T
  <B>(ab: (a: A) => B, ...matchers: readonly [A, LazyArg<B>][]): (a: A) => B
}

export const matchOn: {
  <A>(p: (pattern: A) => (a: A) => boolean): Matchers<A>
} =
  <A>(p: (pattern: A) => (a: A) => boolean) =>
  <B>(ab: (a: A) => B, ...matchers: readonly [A, LazyArg<B>][]) =>
  (a: A): B =>
    pipe (
      matchers,
      readonlyArray.find (([pattern]) => p (pattern) (a)),
      option.match (
        () => ab (a),
        ([, f]) => f (),
      ),
    )

export const matchEq: {
  <A>(Eq: eq.Eq<A>): Matchers<A>
} = Eq => matchOn (Eq.equals)

export const match = matchEq (eq.EqStrict)
