import * as A from "./modules/array"
import * as T from "./modules/task"
import * as TE from "./modules/task-either"
import * as TO from "./modules/task-option"
import * as IO from "./modules/io"
import * as O from "./modules/option"
import * as E from "./modules/either"
import * as I from "./modules/identity"
import * as P from "./modules/predicate"
import { inspect } from "util"
import { URIS } from "./types/Kind"
import { Monad } from "./types/Monad"
import { HKT } from "./types/HKT"
import { Functor } from "./types/Functor"
import { pipe } from "./utils/pipe"
import { wait } from "./utils/wait/task"
import { log_ } from "./utils/console"
import { raise } from "./utils/exceptions"
import { toLowerCase, toUpperCase } from "./utils/strings"

//
