// modules
export * as async from "./modules/Async"
export * as asyncOption from "./modules/AsyncOption"
export * as asyncResult from "./modules/AsyncResult"
export * as boolean from "./modules/Boolean"
export * as duration from "./modules/Duration"
export * as identity from "./modules/Identity"
export * as iterable from "./modules/Iterable"
export * as nonEmptyReadonlyArray from "./modules/NonEmptyReadonlyArray"
export * as number from "./modules/Number"
export * as option from "./modules/Option"
export * as predicate from "./modules/Predicate"
export * as readonlyArray from "./modules/ReadonlyArray"
export * as readonlyRecord from "./modules/ReadonlyRecord"
export * as result from "./modules/Result"
export * as state from "./modules/State"
export * as string from "./modules/String"
export * as sync from "./modules/Sync"
export * as syncOption from "./modules/SyncOption"
export * as syncResult from "./modules/SyncResult"
export * as tree from "./modules/Tree"
export * as json from "./modules/Json"
export * as list from "./modules/List"
export * as matching from "./modules/Matching"
export * as ordering from "./modules/Ordering"
export * as refinement from "./modules/Refinement"

// typeclasses
export * as alt from "./typeclasses/Alt"
export * as alternative from "./typeclasses/Alternative"
export * as applicative from "./typeclasses/Applicative"
export * as applicativeWithIndex from "./typeclasses/ApplicativeWithIndex"
export * as bifunctor from "./typeclasses/Bifunctor"
export * as comonad from "./typeclasses/Comonad"
export * as compactable from "./typeclasses/Compactable"
export * as contravariant from "./typeclasses/Contravariant"
export * as endomorphism from "./typeclasses/Endomorphism"
export * as equivalence from "./typeclasses/Equivalence"
export * as extendable from "./typeclasses/Extendable"
export * as filterable from "./typeclasses/Filterable"
export * as filterableWithIndex from "./typeclasses/FilterableWithIndex"
export * as functor from "./typeclasses/Functor"
export * as functorWithIndex from "./typeclasses/FunctorWithIndex"
export * as group from "./typeclasses/Group"
export { Hkt, Kind } from "./typeclasses/Hkt"
export * as magma from "./typeclasses/Magma"
export * as monad from "./typeclasses/Monad"
export * as monadWithIndex from "./typeclasses/MonadWithIndex"
export * as monoid from "./typeclasses/Monoid"
export { NaturalTransformation } from "./typeclasses/NaturalTransformation"
export * as order from "./typeclasses/Order"
export * as semigroup from "./typeclasses/Semigroup"
export * as show from "./typeclasses/Show"
export * as tappable from "./typeclasses/Tappable"
export * as tappableBoth from "./typeclasses/TappableBoth"
export { TypeClass } from "./typeclasses/TypeClass"

// types
export { DoObject, DoObjectKey } from "./types/DoObject"
export {
  LazyArg,
  Prettify,
  TheseOrAnyNumber,
  TheseOrAnyString,
} from "./types/utils"

// utils
export * from "./utils/absurd"
export * from "./utils/ask"
export * from "./utils/call"
export * as Console from "./utils/console"
export * from "./utils/constant"
export * from "./utils/currying"
export * from "./utils/exceptions"
export * as files from "./utils/files"
export * from "./utils/flow"
export * from "./utils/flip"
export * from "./utils/hole"
export * from "./utils/loops"
export * from "./utils/random"
export * from "./utils/time"
export * from "./utils/typeChecks"
export * from "./utils/underscore"
export * from "./utils/wait"
